- name: remove old docker directory
  file:
    path: '{{ DOCKER_DIR }}'
    state: absent

- name: create new docker directory
  file: 
    path: '{{ DOCKER_DIR }}'
    state: directory
    owner: '{{ FILE_OWNER }}'
    group: '{{ FILE_GROUP }}'
    mode: 0777

- name: copy Dockerfile
  copy:
    src: 'dockerfile/todp-metadata-Dockerfile'
    dest: '{{ DOCKER_DIR }}/Dockerfile'
    owner: '{{ FILE_OWNER }}'
    group: '{{ FILE_GROUP }}'
    mode: 0777

- name: copy docker-compose file
  copy:
    src: 'composefile/todp-metadata-docker-compose.yml'
    dest: '{{ DOCKER_DIR }}/docker-compose.yml'
    owner: '{{ FILE_OWNER }}'
    group: '{{ FILE_GROUP }}'
    mode: 0777

- name: copy rancher-compose file
  copy:
    src: 'composefile/todp-metadata-rancher-compose.yml'
    dest: '{{ DOCKER_DIR }}/rancher-compose.yml'
    owner: '{{ FILE_OWNER }}'
    group: '{{ FILE_GROUP }}'
    mode: 0777

- name: copy config files
  copy:
    src: 'configfile/{{ item }}'
    dest: '{{ DOCKER_DIR }}'
    owner: '{{ FILE_OWNER }}'
    group: '{{ FILE_GROUP }}'
    mode: 0777
  with_items:
    - authorized_keys
    - dp.keytab
    - hdfs.keytab
    - metadata-service
    - todp-metadata.sh

- name: copy supervisord.conf file
  copy:
    src: 'supervisorfile/todp-metadata-supervisord.conf'
    dest: '{{ DOCKER_DIR }}/supervisord.conf'
    owner: '{{ FILE_OWNER }}'
    group: '{{ FILE_GROUP }}'
    mode: 0777
