- name: remove old docker directory
  file:
    path: '{{ DOCKER_DIR }}'
    state: absent

- name: create new docker directory
  file: 
    path: '{{ DOCKER_DIR }}'
    state: directory
    owner: '{{ FILE_OWNER }}'
    group: '{{ FILE_GROUP }}'
    mode: 0777

- name: copy Dockerfile
  copy:
    src: 'dockerfile/robot-Dockerfile'
    dest: '{{ DOCKER_DIR }}/Dockerfile'
    owner: '{{ FILE_OWNER }}'
    group: '{{ FILE_GROUP }}'
    mode: 0777

- name: copy docker-compose file
  copy:
    src: 'composefile/robot-docker-compose.yml'
    dest: '{{ DOCKER_DIR }}/docker-compose.yml'
    owner: '{{ FILE_OWNER }}'
    group: '{{ FILE_GROUP }}'
    mode: 0777

- name: copy rancher-compose file
  copy:
    src: 'composefile/robot-rancher-compose.yml'
    dest: '{{ DOCKER_DIR }}/rancher-compose.yml'
    owner: '{{ FILE_OWNER }}'
    group: '{{ FILE_GROUP }}'
    mode: 0777

- name: copy config files
  copy:
    src: 'configfile/{{ item }}'
    dest: '{{ DOCKER_DIR }}'
    owner: '{{ FILE_OWNER }}'
    group: '{{ FILE_GROUP }}'
    mode: 0777
  with_items:
    - authorized_keys
    - startup.sh

- name: copy supervisord.conf file
  copy:
    src: 'supervisorfile/robot-supervisord.conf'
    dest: '{{ DOCKER_DIR }}/supervisord.conf'
    owner: '{{ FILE_OWNER }}'
    group: '{{ FILE_GROUP }}'
    mode: 0777

- name: tar the source code to tar.gz file
  command: '/usr/bin/tar -zcvf TODP.tar.gz TODP/'
  args:
    chdir: '{{ WORKSPACE }}'

- name: copy source code package to docker service directory
  copy:
    src: '{{ WORKSPACE }}/TODP.tar.gz'
    dest: '{{ DOCKER_DIR }}/'
    owner: '{{ FILE_OWNER }}'
    group: '{{ FILE_GROUP }}'
    mode: 0777
  become: true
  become_method: sudo
  become_user: root

- shell: /bin/date +%Y-%m-%d-%H
  register: result3

- set_fact:
    BACKUP_TIME: '{{ result3.stdout }}'

- name: backup the old robot results
  command: 'mv {{ item }} {{ CEPH_PATH }}/{{ BACKUP_TIME }}-backup'
  with_items:
    - '{{ CEPH_PATH }}/output.xml'
    - '{{ CEPH_PATH }}/report.html'
    - '{{ CEPH_PATH }}/log.html'
  ignore_errors: True


